# Generated by Django 4.1.1 on 2022-09-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='resumen',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
